DROP TABLE IF EXISTS PokeCup_TorneioJogador;
DROP TABLE IF EXISTS PokeCup_TorneioPartida;
DROP TABLE IF EXISTS PokeCup_Ronda;
DROP TABLE IF EXISTS PokeCup_Partida;
DROP TABLE IF EXISTS PokeCup_ResultadoFinal;
DROP TABLE IF EXISTS PokeCup_Torneio;
DROP TABLE IF EXISTS PokeCup_EquipaPokemons;
DROP TABLE IF EXISTS PokeCup_PokemonEscolhido;
DROP TABLE IF EXISTS PokeCup_Jogador;
DROP TABLE IF EXISTS PokeCup_Pokemons;
DROP TABLE IF EXISTS PokeCup_Ataque;
DROP TABLE IF EXISTS PokeCup_Item;

DROP FUNCTION IF EXISTS GetPokemonsEscolhidos;
DROP FUNCTION IF EXISTS GetPokemonsFromTier;
DROP FUNCTION IF EXISTS GetEquipaFromJogador;
DROP FUNCTION IF EXISTS GetEquipaFromJogadorFromTier;
