INSERT INTO Item VALUES
    ('Air Balloon','When held by a Pokémon, the Pokémon will float into the air. When the holder is attacked, this item will burst.'),
    ('Choice Band','Raises Attack, but only one move can be used.'),
    ('Choice Scarf','Raises Speed, but only one move can be used.'),
    ('Choice Specs','Raises Special Attack, but only one move can be used.'),
    ('Expert Belt','Increases the power of super-effective moves.'),
    ('Flame Orb','An item to be held by a Pokémon. It is a bizarre orb that inflicts a burn on the holder in battle.'),
    ('Focus Sash','An item to be held by a Pokémon. If it has full HP, the holder will endure one potential KO attack, leaving 1 HP.'),
    ('Leftovers',"An item to be held by a Pokémon. The holder's HP is gradually restored during battle."),
    ('Life Orb','Increases the power of moves, but loses HP each turn.'),
    ('Muscle Band','Increases the power of Physical-category moves.'),
    ('Rocky Helmet','If the holder of this item takes damage, the attacker will also be damaged upon contact.'),
    ('Toxic Orb','An item to be held by a Pokémon. It is a bizarre orb that badly poisons the holder in battle.'),
    ('Wise Glasses','Increases the power of Special-category moves.');

INSERT INTO Ataque VALUES
    ('Bug Buzz','Bug',90,100,'Special'),
    ('X-Scissor','Bug',80,100,'Physical'),
    ('Crunch','Dark',80,100,'Physical'),
    ('Night Daze','Dark',85,85,'Special'),
    ('Outrage','Dragon',120,100,'Physical'),
    ('Draco Meteor','Dragon',140,90,'Special'),
    ('Thunder','Electric',120,70,'Special'),
    ('Volt Tackle','Electric',120,100,'Physical'),
    ('Close Combat','Fighting',120,100,'Physical'),
    ('Focus Blast','Fighting',120,70,'Special'),
    ('Flare Blitz','Fire',120,100,'Physical'),
    ('Overheat','Fire',140,90,'Special'),
    ('Brave Bird','Flying',120,100,'Physical'),
    ('Hurricane','Flying',120,70,'Special'),
    ('Shadow Ball','Ghost',80,100,'Special'),
    ('Shadow Claw','Ghost',70,100,'Physical'),
    ('Leaf Storm','Grass',140,90,'Special'),
    ('Power Whip','Grass',120,85,'Physical'),
    ('Earthquake','Ground',100,100,'Physical'),
    ('Earth Power','Ground',90,100,'Special'),
    ('Blizzard','Ice',120,70,'Special'),
    ('Ice Punch','Ice',75,100,'Physical'),
    ('Double-Edge','Normal',120,100,'Physical'),
    ('Hyper Voice','Normal',90,100,'Special'),
    ('Gunk Shot','Poison',120,70,'Physical'),
    ('Sludge Wave','Poison',95,100,'Special'),
    ('Zen Headbutt','Psychic',80,90,'Physical'),
    ('Psystrike','Psychic',100,100,'Special'),
    ('Stone Edge','Rock',100,80,'Physical'),
    ('Power Gem','Rock',80,100,'Special'),
    ('Iron Tail','Steel',100,75,'Physical'),
    ('Flash Cannon','Steel',80,100,'Special'),
    ('Aqua Tail','Water',90,90,'Physical'),
    ('Hydro Pump','Water',120,80,'Special');

INSERT INTO Pokemons VALUES
    (494,'Victini','../pokemon_images/494.png','Psychic','Fire','UU'),
    (497,'Serperior','../pokemon_images/497.png','Grass','','NU'),
    (500,'Emboar','../pokemon_images/500.png','Fire','Fighting','RU'),
    (503,'Samurott','../pokemon_images/503.png','Water','','NU'),
    (508,'Stoutland','../pokemon_images/508.png','Normal','','PU'),
    (523,'Zebstrika','../pokemon_images/523.png','Electric','','PU'),
    (530,'Excadrill','../pokemon_images/530.png','Ground','Steel','OU'),
    (534,'Conkeldurr','../pokemon_images/534.png','Fighting','','OU'),
    (537,'Seismitoad','../pokemon_images/537.png','Water','Ground','NU'),
    (553,'Krookodile','../pokemon_images/553.png','Ground','Dark','UU'),
    (555,'Darmanitan','../pokemon_images/555.png','Fire','','UU'),
    (560,'Scrafty','../pokemon_images/560.png','Dark','Fighting','UU'),
    (563,'Cofagrigus','../pokemon_images/563.png','Ghost','','UU'),
    (565,'Carracosta','../pokemon_images/565.png','Water','Rock','NU'),
    (567,'Archeops','../pokemon_images/567.png','Rock','Flying','RU'),
    (571,'Zoroark','../pokemon_images/571.png','Dark','','UU'),
    (576,'Gothitelle','../pokemon_images/576.png','Psychic','','OU'),
    (579,'Reuniclus','../pokemon_images/579.png','Psychic','','OU'),
    (584,'Vanilluxe','../pokemon_images/584.png','Ice','','PU'),
    (589,'Escavalier','../pokemon_images/589.png','Bug','Steel','RU'),
    (593,'Jellicent','../pokemon_images/593.png','Water','Ghost','OU'),
    (596,'Galvantula','../pokemon_images/596.png','Bug','Electric','RU'),
    (598,'Ferrothorn','../pokemon_images/598.png','Grass','Steel','OU'),
    (604,'Eelektross','../pokemon_images/604.png','Electric','','NU'),
    (609,'Chandelure','../pokemon_images/609.png','Ghost','Fire','OU'),
    (612,'Haxorus','../pokemon_images/612.png','Dragon','','OU'),
    (614,'Beartic','../pokemon_images/614.png','Ice','','PU'),
    (617,'Accelgor','../pokemon_images/617.png','Bug','','RU'),
    (620,'Mienshao','../pokemon_images/620.png','Fighting','','UU'),
    (621,'Druddigon','../pokemon_images/621.png','Dragon','','RU'),
    (623,'Golurk','../pokemon_images/623.png','Ground','Ghost','NU'),
    (625,'Bisharp','../pokemon_images/625.png','Dark','Steel','UU'),
    (628,'Braviary','../pokemon_images/628.png','Normal','Flying','NU'),
    (630,'Mandibuzz','../pokemon_images/630.png','Dark','Flying','NU'),
    (635,'Hydreigon','../pokemon_images/635.png','Dark','Dragon','OU'),
    (637,'Volcarona','../pokemon_images/637.png','Bug','Fire','OU'),
    (638,'Cobalion','../pokemon_images/638.png','Steel','Fighting','UU'),
    (639,'Terrakion','../pokemon_images/639.png','Rock','Fighting','OU'),
    (640,'Virizion','../pokemon_images/640.png','Grass','Fighting','UU'),
    (641,'Tornadus','../pokemon_images/641.png','Flying','','UU'),
    (642,'Thundurus','../pokemon_images/642.png','Electric','Flying','Uber'),
    (643,'Reshiram','../pokemon_images/643.png','Dragon','Fire','Uber'),
    (644,'Zekrom','../pokemon_images/644.png','Dragon','Electric','Uber'),
    (645,'Landorus','../pokemon_images/645.png','Ground','Flying','Uber'),
    (646,'Kyurem','../pokemon_images/646.png','Dragon','Ice','OU'),
    (647,'Keldeo','../pokemon_images/647.png','Water','Fighting','OU'),
    (648,'Meloetta','../pokemon_images/648.png','Normal','Psychic','UU'),
    (649,'Genesect','../pokemon_images/649.png','Bug','Steel','Uber'),